### ISSUE TITLE
Bug: error message "Your file was not found"

### ISSUE THREAD

**Issue by tarafanlin** [jasonleyser/slate-for-chrome#3]
This happens to me just now when I was trying to save an image.
<img width="1440" alt="Screen Shot 2020-09-15 at 9 53 14 AM" src="https://user-images.githubusercontent.com/35607644/93241054-b8921780-f739-11ea-979b-4438917fa437.png">

**Comment by jasonleyser** [comment]
@tarafanlin do you mean save it to your computer or to slate?

**Comment by tarafanlin** [comment]
> @tarafanlin do you mean save it to your computer or to slate?

when I save it to slate with the chrome extension

**Comment by jasonleyser** [comment]
> when I save it to slate with the chrome extension

Okay thanks. Is it happening with every image now?

**Comment by tarafanlin** [comment]
> > when I save it to slate with the chrome extension
> 
> Okay thanks. Is it happening with every image now?

yep, and screenshots as well

**Comment by tarafanlin** [comment]
I delete and reupload the extension and it's working now. Not sure why this bug earlier.  But closing this for now until I reproduce the bug.

**Comment by jasonleyser** [comment]
@tarafanlin im thinking something happened with the file structure. I was getting this error last night when I was moving the files into their build and src folders and that error would show up when i didn't correctly link the file. 

Good to hear its back though! Thanks again for flagging this
